### PR TITLE
super almost done, waiting on Ed

### PR DESCRIPTION
**Pull request by sanchezfernandes**
-Super almost done, everything works and looks good.
-Waiting on Ed and then will make the last changes.

### CODE REVIEW

**Review by Edthev — APPROVED** [review]
Checked and it is great

**Review by Edthev — APPROVED** [review]

**Review by trumerfe — CHANGES_REQUESTED** [review]
For desktop size, make the modal fixed 672px wide with margins on auto for responsiveness, other than that, great job!

**Review by jwuzzle — COMMENTED** [review]
@sanchezfernandes on lines 31,32 where it says "....content__title'>Delete Washington warehouse?</h2>" Is this modal code for just the Washington warehouse or will the Washington copy here be swapped out and pulled from the database?

**Comment by sanchezfernandes** [comment]
> @sanchezfernandes on lines 31,32 where it says "....content__title'>Delete Washington warehouse?" Is this modal code for just the Washington warehouse or will the Washington copy here be swapped out and pulled from the database?

No that was just a place holder, was waiting on the Warehouse List page to connect into it.

**Comment by sanchezfernandes** [comment]
> For desktop size, make the modal fixed 672px wide with margins on auto for responsiveness, other than that, great job!

Got it, I can do that on the next PR which should be the final for the warhorse modal

**Review by jwuzzle — APPROVED** [review]

**Review by trumerfe — APPROVED** [review]

**Pull request merged**
